### ISSUE TITLE
Responsive Icon hit area too big

### ISSUE THREAD

**Issue by ryansegus** [gitFoxCode/nuxt-icons#31]
Hi, great work!

I just found an issue and I was wondering if this could help in any way. In the CSS you declare this:

```css
.nuxt-config svg {
    width: 1em;
    height: 1em; // <-- This is causing a huge hit area for rectangle svg's
    margin-bottom: 0.125em; // <-- This should be choose by the developer
    vertical-align: middle;
}
```

Right now I am overriding these 2 rules with !important which works fine but I think this can be improved. As you can see in the next image the hit area is perfectly align with the svg itself.

<img width="1001" alt="Screenshot 2022-12-07 at 16 16 00" src="https://user-images.githubusercontent.com/7275531/206218176-58f44994-0b59-47a0-91ca-1dea094c9d9e.png">

On the other hand, the next image shows the bigger hit area, this could possibly cause issues when dealing with other elements on the page.

<img width="1013" alt="Screenshot 2022-12-07 at 16 16 15" src="https://user-images.githubusercontent.com/7275531/206218347-c59b6355-af2e-4fd1-a927-635fd7b54e44.png">

For the height issue I suggest just using height: auto as default.
For the margin bottom I suggest using css-vars instead, something like `margin-botton: var(--ni-margin-bottom, '0')`, this way we as developers could override the value without the need of !important rules. Also noticed that I suggested 0 instead of 0.125em because having margings on SVG could cause UI design issues when dealing with icon buttons and suchs.

**Comment by gitFoxCode** [comment]
Hey, thanks for this thread! This module was intended to be used for icons used a bit like text or next to text, using it to e.g. post a logo is also ok but causes those errors you got. I made the assumption that if someone wants to use these icons for another purpose they will modify their CSS globally (without writing !important):
```css
.nuxt-icon svg{
    width: x;
    height: y;
}
```
but I will think about the option for castomization
